export const dashboardKpis = [
  { label: "Fermes actives", value: "12" },
  { label: "Parcelles suivies", value: "148" },
  { label: "Interventions aujourd'hui", value: "37" },
  { label: "Alertes critiques", value: "6" },
  { label: "Taux de cloture", value: "91%" },
  { label: "Preuves photo recues", value: "284" },
];

export const farmCards = [
  {
    name: "Ferme de Mbankana",
    manager: "Alain N.",
    surface: "86 ha",
    plots: 24,
    teams: 5,
    openOps: 9,
    incidents: 2,
    status: "Sous surveillance",
    report: "il y a 12 min",
    crops: "Mais, manioc, maraichage",
  },
  {
    name: "Ferme Kintele",
    manager: "Joelle M.",
    surface: "120 ha",
    plots: 31,
    teams: 6,
    openOps: 12,
    incidents: 3,
    status: "Alerte elevee",
    report: "il y a 18 min",
    crops: "Manioc, mais, maraichage",
  },
  {
    name: "Ferme Nord",
    manager: "Patrick B.",
    surface: "64 ha",
    plots: 19,
    teams: 4,
    openOps: 7,
    incidents: 1,
    status: "En activite normale",
    report: "il y a 6 min",
    crops: "Tomate, mais",
  },
];

export const interventionsRows = [
  {
    type: "Irrigation",
    farm: "Ferme Nord",
    plot: "B12",
    team: "Equipe A",
    hour: "08:30",
    status: "En cours",
    priority: "Haute",
  },
  {
    type: "Recolte",
    farm: "Zone Ouest",
    plot: "D04",
    team: "Equipe Recolte 2",
    hour: "07:15",
    status: "Terminee",
    priority: "Moyenne",
  },
  {
    type: "Inspection sanitaire",
    farm: "Kintele",
    plot: "A03",
    team: "Superviseur 1",
    hour: "10:00",
    status: "A faire",
    priority: "Haute",
  },
];

export const incidentRows = [
  {
    incident: "Suspicion maladie foliaire",
    farm: "Kintele",
    zone: "A03",
    category: "sanitaire",
    criticality: "Critique",
    reporter: "Superviseur 1",
    date: "04/04 09:12",
    status: "En investigation",
    assignee: "Expert phyto",
  },
  {
    incident: "Pompe hors service",
    farm: "Station Sud",
    zone: "S2",
    category: "materiel",
    criticality: "Critique",
    reporter: "Maintenance",
    date: "04/04 07:44",
    status: "Assigne",
    assignee: "Technicien M3",
  },
  {
    incident: "Niveau eau insuffisant",
    farm: "Ferme Nord",
    zone: "A3",
    category: "irrigation",
    criticality: "Eleve",
    reporter: "Equipe A",
    date: "04/04 08:55",
    status: "Ouvert",
    assignee: "Chef irrigation",
  },
];
